### ISSUE TITLE
Newest SchleFaz Movies does not work.

### ISSUE THREAD

**Issue by dreyloft** [simon-wessel/schleflix#1]
Since the Movie "Lass jucken Kumpel" this script seems to stopped working correctly for newer Movies. Possible issue is that "Lass jucken Kumpel" was a movie for 18+ years old only.

**Comment by simon-wessel** [comment]
Hi dreyloft,
does the problem still appear for you? Otherwise I'd close the issue as long as it does not reappear. The movie you mentioned is not currently available as far as I can see.
Kind regards
